// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnboardRoom.Infrastructure.Data;

#nullable disable

namespace OnboardRoom.Infrastructure.Data.Migrations
{
    [DbContext(typeof(OnboardRoomDbContext))]
    [Migration("20260611225514_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("OnboardRoom.Domain.Entities.GroupChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "Sequence")
                        .IsUnique();

                    b.ToTable("GroupChatMessages", (string)null);
                });

            modelBuilder.Entity("OnboardRoom.Domain.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChairRecommendationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalOutputHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputTextOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputTextRedacted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRounds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RerunFromStep")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RootRunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RootRunId");

                    b.HasIndex("Status");

                    b.ToTable("WorkflowRuns", (string)null);
                });

            modelBuilder.Entity("OnboardRoom.Domain.Entities.WorkflowStepRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StepName")
                        .IsUnique();

                    b.HasIndex("RunId", "StepOrder");

                    b.ToTable("WorkflowStepRuns", (string)null);
                });

            modelBuilder.Entity("OnboardRoom.Domain.Entities.GroupChatMessage", b =>
                {
                    b.HasOne("OnboardRoom.Domain.Entities.WorkflowRun", "Run")
                        .WithMany("Messages")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("OnboardRoom.Domain.Entities.WorkflowStepRun", b =>
                {
                    b.HasOne("OnboardRoom.Domain.Entities.WorkflowRun", "Run")
                        .WithMany("Steps")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("OnboardRoom.Domain.Entities.WorkflowRun", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
