// Copyright (c) Microsoft. All rights reserved.

using System.Text;
using OnboardFlow.Application.Interfaces;
using OnboardFlow.Domain.ValueObjects;

namespace OnboardFlow.Application.Executors;

/// <summary>
/// Step 6: Generate the final HTML package with decision summary and audit trail.
/// Non-LLM step — pure template rendering.
/// </summary>
public sealed class FinalPackageExecutor : IStepExecutor
{
    public string StepName => WorkflowSteps.FinalPackage;

    public Task<OnboardingContext> ExecuteAsync(OnboardingContext context, CancellationToken cancellationToken = default)
    {
        var decisionPack = DecisionPack.FromJson(context.DecisionPackJson ?? "{}");
        var profile = ApplicantProfile.FromJson(context.ApplicantProfileJson ?? "{}");

        var html = new StringBuilder();
        html.AppendLine("<!DOCTYPE html>");
        html.AppendLine("<html><head><meta charset='utf-8'><title>OnboardFlow Report</title></head><body>");
        html.AppendLine("<h1>Onboarding Decision Report</h1>");

        // Applicant summary
        html.AppendLine("<h2>Applicant</h2>");
        html.AppendLine($"<p><strong>Company:</strong> {Encode(profile.CompanyName)}</p>");
        html.AppendLine($"<p><strong>Contact:</strong> {Encode(profile.ContactName)}</p>");
        html.AppendLine($"<p><strong>Region:</strong> {Encode(profile.Region)}</p>");

        // Overall recommendation
        html.AppendLine("<h2>Recommendation</h2>");
        html.AppendLine($"<p class='recommendation'>{Encode(decisionPack.OverallRecommendation)}</p>");

        // Conditions
        if (decisionPack.Conditions.Count > 0)
        {
            html.AppendLine("<h3>Conditions</h3><ul>");
            foreach (var condition in decisionPack.Conditions)
            {
                html.AppendLine($"<li>{Encode(condition)}</li>");
            }
            html.AppendLine("</ul>");
        }

        // Merged findings
        if (decisionPack.MergedFindings.Count > 0)
        {
            html.AppendLine("<h3>Key Findings</h3><table border='1' cellpadding='4'>");
            html.AppendLine("<tr><th>Category</th><th>Finding</th><th>Severity</th></tr>");
            foreach (var finding in decisionPack.MergedFindings)
            {
                html.AppendLine($"<tr><td>{Encode(finding.Category)}</td><td>{Encode(finding.Title)}</td><td>{Encode(finding.Severity)}</td></tr>");
            }
            html.AppendLine("</table>");
        }

        // Conflicts
        if (decisionPack.Conflicts.Count > 0)
        {
            html.AppendLine("<h3>Review Conflicts</h3><ul>");
            foreach (var conflict in decisionPack.Conflicts)
            {
                html.AppendLine($"<li><strong>{Encode(conflict.Topic)}</strong>");
                html.AppendLine("<ul>");
                foreach (var opinion in conflict.Opinions)
                {
                    html.AppendLine($"<li>{Encode(opinion.Agent)}: {Encode(opinion.Text)}</li>");
                }
                html.AppendLine("</ul></li>");
            }
            html.AppendLine("</ul>");
        }

        // Customer next steps
        if (!string.IsNullOrWhiteSpace(context.CustomerNextSteps))
        {
            html.AppendLine("<h2>Customer Next Steps</h2>");
            html.AppendLine($"<p>{Encode(context.CustomerNextSteps)}</p>");
        }

        // Warnings
        if (context.Warnings.Count > 0)
        {
            html.AppendLine("<h2>Warnings</h2><ul>");
            foreach (var warning in context.Warnings)
            {
                html.AppendLine($"<li>{Encode(warning)}</li>");
            }
            html.AppendLine("</ul>");
        }

        // Audit trail
        html.AppendLine("<hr/><footer><small>Generated by OnboardFlow</small></footer>");
        html.AppendLine("</body></html>");

        context.FinalHtml = html.ToString();

        return Task.FromResult(context);
    }

    private static string Encode(string? value)
        => System.Net.WebUtility.HtmlEncode(value ?? string.Empty);
}
